# Generated by Django 3.1.1 on 2020-11-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201101_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='timestamp',
        ),
    ]
