# Generated by Django 3.1.1 on 2020-12-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isEditor',
            field=models.BooleanField(default=False),
        ),
    ]
