# Generated by Django 3.1.1 on 2020-12-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201222_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Saved',
            field=models.ManyToManyField(blank=True, to='webapp.Media'),
        ),
    ]
