# Generated by Django 3.1.1 on 2020-09-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0002_auto_20200916_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments',
                                    to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(
                choices=[('Other', 'Other'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Home', 'Home'),
                         ('Toys', 'Toys')], default='Other', max_length=64),
        ),
    ]
