# Generated by Django 3.1.1 on 2020-09-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0003_auto_20200916_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(
                choices=[('Home', 'Home'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Other', 'Other'),
                         ('Toys', 'Toys')], default='Other', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.ForeignKey(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                              related_name='listing_start', to='auctions.bid'),
                                    null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='listing_current', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, max_length=1084),
        ),
    ]
